In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
data = pd.read_csv('train_data.csv')


In [4]:
data.head()

Unnamed: 0         Image          R           G           B   Contrast  \
0           0  DSC03672.JPG  35.019852  156.003722  120.733321  33.427004   
1           1  DSC03673.JPG  67.234275  191.549269  157.974661  45.049262   
2           2  DSC03674.JPG  81.729594  200.065917  168.925371  48.057253   
3           3  DSC03675.JPG  46.449320  163.743535  132.749118  40.541535   
4           4  DSC03676.JPG  44.298968  163.979309  130.859399  39.470236   

   Brightness        y_R         y_G         y_B  y_Contrast  y_Brightness  
0   88.865257  53.391474  201.865541  150.053827   51.590215     76.670915  
1   69.016516  63.093017  205.004082  161.341813   55.443302     70.631014  
2   64.006360  70.593650  212.716109  178.108053   62.726450     73.407497  
3   81.118127  57.301819  196.353726  152.783891   53.439644     75.311232  
4   81.539691  54.697028  196.917517  150.698785   52.907086     75.685523

In [16]:
X = data[['R','G','B','Contrast','Brightness']]
y = data[['y_R','y_G','y_B','y_Contrast','y_Brightness']]

In [17]:
X = X.to_numpy()
y = y.to_numpy()


In [18]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size = 0.25)


In [19]:
X_train

array([[ 56.40077513, 160.8512083 , 129.2907364 ,  41.65281439,
         74.02102621],
       [ 66.99255767, 154.4134384 , 130.5870729 ,  38.44645033,
         69.47827088],
       [ 47.77916279, 144.6648168 , 113.815626  ,  36.18217634,
         68.39481825],
       ...,
       [ 60.56041421, 163.9023641 , 138.8403695 ,  40.22760247,
         85.85824767],
       [ 50.61340252,  35.39988204,  42.90048905,  17.6170093 ,
         36.70806775],
       [ 68.39046713, 140.2713797 , 121.6382635 ,  34.73302662,
         61.38244933]])

In [20]:
X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)
y_train = torch.Tensor(y_train)
y_test = torch.Tensor(y_test)

In [21]:
class ANN_model(nn.Module):
    def __init__(self,input_features=5,hidden1 = 50,hidden2 = 50,hidden3 = 45,out_features=5):
        super().__init__()
        self.fully_connected1 = nn.Linear(input_features,hidden1)
        self.fully_connected2 = nn.Linear(hidden1,hidden2)
        self.fully_connected3 = nn.Linear(hidden2,hidden3)
        self.out = nn.Linear(hidden3,out_features)
    def forward(self,x):
        x = F.relu(self.fully_connected1(x))
        x = F.relu(self.fully_connected2(x))
        x = F.relu(self.fully_connected3(x))
        x = self.out(x)
        return x



In [22]:
torch.manual_seed(20)
model = ANN_model()

loss_function = nn.L1Loss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.04)

In [38]:
y_train

tensor([[ 30.1174, 185.2516, 135.8235,  52.2155, 107.4449],
        [ 60.5996, 193.9066, 153.3245,  63.4297,  82.7506],
        [ 23.3027, 169.7754, 105.1831,  49.9784,  98.3162],
        ...,
        [ 39.6824, 183.5883, 142.5553,  39.7669, 118.3089],
        [117.0886,  86.8151, 101.3602,  45.8326,  90.1179],
        [ 53.5981, 159.4688, 119.8872,  45.5524,  72.3800]])

In [24]:
epochs = 800
final_losses=[]
for i in range(epochs):
    i+=1
    y_pred = model.forward(X_train)
    loss = loss_function(y_pred,y_train)
    final_losses.append(loss)
    if i%10== 1:
        print("Epoch Number:{} and loss: {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch Number:1 and loss: 8.233614921569824
Epoch Number:11 and loss: 8.800740242004395
Epoch Number:21 and loss: 8.463773727416992
Epoch Number:31 and loss: 8.952302932739258
Epoch Number:41 and loss: 7.988983631134033
Epoch Number:51 and loss: 8.169184684753418
Epoch Number:61 and loss: 7.871326446533203
Epoch Number:71 and loss: 8.330317497253418
Epoch Number:81 and loss: 8.16981029510498
Epoch Number:91 and loss: 8.62421989440918
Epoch Number:101 and loss: 8.377964973449707
Epoch Number:111 and loss: 8.303437232971191
Epoch Number:121 and loss: 10.150906562805176
Epoch Number:131 and loss: 7.85744571685791
Epoch Number:141 and loss: 7.750137805938721
Epoch Number:151 and loss: 7.432345867156982
Epoch Number:161 and loss: 7.946929931640625
Epoch Number:171 and loss: 7.739403247833252
Epoch Number:181 and loss: 8.851107597351074
Epoch Number:191 and loss: 8.035443305969238
Epoch Number:201 and loss: 7.311936855316162
Epoch Number:211 and loss: 9.810372352600098
Epoch Number:221 and lo

In [35]:
 for i,data in enumerate(X_test):
  print(i,data)

0 tensor([ 46.8822, 141.9085, 112.8431,  36.4610,  68.7633])
1 tensor([ 53.8827, 150.8241, 118.9811,  30.0510,  64.3085])
2 tensor([ 46.6790, 143.4324, 111.3230,  34.4794,  63.6656])
3 tensor([ 55.1101, 159.8802, 128.3756,  41.1449,  74.2514])
4 tensor([74.1114, 64.4950, 78.2898, 23.3107, 56.4565])
5 tensor([ 43.8804, 146.0584, 118.3655,  37.3872,  82.5062])
6 tensor([ 58.7051, 118.3307, 105.1043,  38.5013,  58.1040])
7 tensor([80.9111, 84.8072, 95.0180, 51.0815, 81.1619])
8 tensor([ 54.7731, 152.8067, 122.4995,  36.1316,  75.2114])
9 tensor([ 69.6473,  83.4839, 131.1935,  48.8331, 109.9230])
10 tensor([ 46.1971, 142.7102, 111.9429,  36.1441,  69.2964])
11 tensor([ 75.9592, 160.4743, 145.8477,  44.0940,  79.3034])
12 tensor([ 64.1640, 146.0916, 126.1150,  42.0521,  63.8866])
13 tensor([ 85.8023, 167.5187, 147.0743,  51.2897,  85.4388])
14 tensor([ 67.5764,  79.7778, 102.0181,  31.3762,  73.2817])
15 tensor([ 81.7296, 200.0659, 168.9254,  48.0573,  64.0064])
16 tensor([ 43.8420, 146.549

In [46]:
pred = []
with torch.no_grad():
    for i,data in enumerate(X_test):
        y_pred = model(data)
        pred.append(y_pred.tolist())
        

In [29]:
from sklearn.metrics import mean_absolute_error

In [48]:
pred  = torch.Tensor(pred)

In [43]:
y_test

tensor([[ 22.4110, 166.0547, 104.2006,  50.5261,  98.3892],
        [ 40.2862, 180.7822, 113.9092,  49.5130,  66.8342],
        [ 48.4937, 172.6582, 124.2180,  48.2834,  63.2702],
        [ 30.0271, 184.4891, 135.1822,  51.0447, 105.6258],
        [129.6111, 109.3063, 129.6007,  64.4435, 112.3333],
        [ 20.6347, 175.9971, 118.4708,  40.3390, 115.3824],
        [ 48.8457, 137.4653,  98.8283,  55.8184,  84.9990],
        [138.2980, 141.5339, 156.8327,  59.7031, 112.8090],
        [ 46.3860, 194.8123, 143.4035,  58.1293,  94.1631],
        [ 85.5722,  97.6947, 155.3053,  58.4452, 126.4338],
        [ 22.2610, 168.0884, 103.2450,  49.1102,  97.4390],
        [ 55.6780, 178.0401, 150.9428,  45.5203, 115.0022],
        [ 56.3545, 179.9168, 141.3873,  68.5309,  80.5190],
        [ 70.1189, 189.3022, 154.7728,  49.1945, 104.6643],
        [ 80.5569,  85.8886, 104.0642,  42.6135,  76.0099],
        [ 70.5937, 212.7161, 178.1080,  62.7265,  73.4075],
        [ 18.1069, 171.3580, 104.8203,  

In [49]:
mean_absolute_error(pred,y_test)

8.228266

In [55]:
torch.save(model,'pixelmodel.pt')

model = torch.load('pixelmodel.pt')
val = torch.Tensor([[51.71115833333333, 127.93539166666666, 115.67108125, 0.9919028340080972, 115.57905208333334]])
# model.eval(val)
model(val)


tensor([[ 70.2505, 248.0688, 182.4282,  64.3848,  80.1765]],
       grad_fn=<AddmmBackward0>)

In [56]:
df = pd.read_csv('test_values_x.csv')

In [60]:
pred_val = df[['R','G','B','Contrast','Brightness']]
pred_val = pred_val.to_numpy()


In [62]:
values = model(torch.Tensor(pred_val))

In [64]:
values = values.tolist()
values

[[57.802345275878906,
  154.54885864257812,
  117.6202163696289,
  43.61363220214844,
  85.19639587402344],
 [42.0350227355957,
  149.80596923828125,
  113.09626007080078,
  43.966487884521484,
  95.60227966308594],
 [39.458255767822266,
  147.7364501953125,
  111.36418914794922,
  43.65437698364258,
  95.38600158691406],
 [44.815608978271484,
  152.8433074951172,
  114.11905670166016,
  44.15391159057617,
  89.73619842529297],
 [119.4686508178711,
  86.60689544677734,
  123.9814453125,
  49.069190979003906,
  108.02983856201172],
 [110.16243743896484,
  83.14086151123047,
  117.75636291503906,
  47.93901062011719,
  101.7511215209961],
 [102.00543975830078,
  76.55023193359375,
  110.31214141845703,
  46.05470275878906,
  95.8355941772461],
 [77.71517181396484,
  81.16861724853516,
  105.57491302490234,
  58.53571701049805,
  86.33081817626953],
 [82.79432678222656,
  84.78434753417969,
  103.3702163696289,
  59.320953369140625,
  84.20561981201172],
 [80.53446197509766,
  84.45777893